### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by milktrader** [JuliaQuant/FinancialBlotter.jl#21]
Implement the following

~~Create metadata types:~~ moved to FinancialSeries package

- [ ] Trading instrument types
- [x] `Stock`
- [ ] `Future`
- [ ] `Option`
- [x] `Currency`
- [x] `CurrencyPair`
- [ ] `Bond`

~~Time series type specific to financial time series~~ moved to FinancialSeries

- [x] `FinancialTimeSeries` type

~~Function that accepts a discrete signal array (`TimeArray`) and processes rules~~
Function that accepts a `MarketSignal` and processes rules

- [ ] Trading Algorithm

A type that accepts orders from a trading algorithm

- [ ] `OrderBook` type

Function that simulates real trading environments 

- [ ] Fill simulator engine

An accounting framework and statistics

- [x] `Blotter` type
- [ ] trade statistics methods based on `Blotter`
- [ ] portfolio statistics methods based on `Blotter`

**Comment by milktrader** [comment]
This issue belongs in the Roadmap repository. Closing it here with a reference for posterity.
